### ISSUE TITLE
Submitting GPG signing key to OpenTofu registry

### ISSUE THREAD

**Issue by Doridian** [mangadex-pub/terraform-provider-cloudns#110]
As an Open Source enthusiast, I would love to switch over fully to OpenTofu.

I have noticed this provider does not yet have its key in the OpenTofu registry.

I have added my own key to the registry already and adding a new key is easily done via the "Submit new Provider Signing Key" link here: https://github.com/opentofu/registry?tab=readme-ov-file ( or the direct link: https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+ )

**Comment by Tristan971** [comment]
Hello, that's interesting! I will submit our signing key there :+1: 

Thanks for the suggestion

**Comment by Tristan971** [comment]
Done and merged there. See https://github.com/opentofu/registry/pull/384

You will need to pull the just-released version with it though, as I had to replace the by-now-long-expired (...) GPG key we used to use.

Let me know if you run into any trouble.
